apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: comp-2048-ummw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: comp-2048-ummw
    app.kubernetes.io/part-of: sho-2048
  name: comp-2048-ummw
  namespace: showeimer-tenant
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: comp-2048-ummw
    weight: 100
status: {}
